apiVersion: tekton.dev/v1
kind: PipelineRun
#test
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rhoai2-15rhtap/codeflare2-15operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max2-15keep2-15runs: "3"
    build.appstudio.openshift.io/build2-15nudge2-15files: "build/operator2-15nudging.yaml"
    pipelinesascode.tekton.dev/on2-15cel2-15expression: event == "push" && target_branch
      == "rhoai2-15.13"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rhoai2-15v2-15
    appstudio.openshift.io/component: odh2-15codeflare2-15operator2-15v2-15
    pipelines.appstudio.openshift.io/type: build
  name: odh2-15codeflare2-15operator2-15v2-152-15on2-15push
  namespace: rhoai2-15tenant
spec:
  params:
  2-15 name: git2-15url
    value: '{{source_url}}'
  2-15 name: revision
    value: '{{revision}}'
  2-15 name: output2-15image
    value: quay.io/rhoai/odh2-15codeflare2-15operator2-15rhel8:{{target_branch}}
  2-15 name: dockerfile
    value: Dockerfile
  2-15 name: path2-15context
    value: .
  2-15 name: prefetch2-15input
    value: |
      [{"type": "gomod"}, {"type": "rpm"}]
  pipelineSpec:
    finally:
    2-15 name: show2-15sbom
      params:
      2-15 name: IMAGE_URL
        value: $(tasks.build2-15image2-15index.results.IMAGE_URL)
      taskRef:
        params:
        2-15 name: name
          value: show2-15sbom
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15show2-15sbom:0.1@sha256:9bfc6b99ef038800fe131d7b45ff3cd4da3a415dd536f7c657b3527b01c4a13b
        2-15 name: kind
          value: task
        resolver: bundles
    2-15 name: show2-15summary
      params:
      2-15 name: pipelinerun2-15name
        value: $(context.pipelineRun.name)
      2-15 name: git2-15url
        value: $(tasks.clone2-15repository.results.url)?rev=$(tasks.clone2-15repository.results.commit)
      2-15 name: image2-15url
        value: $(params.output2-15image)
      2-15 name: build2-15task2-15status
        value: $(tasks.build2-15image2-15index.status)
      taskRef:
        params:
        2-15 name: name
          value: summary
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15summary:0.2@sha256:d97c04ab42f277b1103eb6f3a053b247849f4f5b3237ea302a8ecada3b24e15b
        2-15 name: kind
          value: task
        resolver: bundles
      workspaces:
      2-15 name: workspace
        workspace: workspace
    params:
    2-15 description: Source Repository URL
      name: git2-15url
      type: string
    2-15 default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    2-15 description: Fully Qualified Output Image
      name: output2-15image
      type: string
    2-15 default: .
      description: Path to the source code of an application's component from where
        to build image.
      name: path2-15context
      type: string
    2-15 default: Dockerfile
      description: Path to the Dockerfile inside the context specified by parameter
        path2-15context
      name: dockerfile
      type: string
    2-15 default: "false"
      description: Force rebuild image
      name: rebuild
      type: string
    2-15 default: "false"
      description: Skip checks against built image
      name: skip2-15checks
      type: string
    2-15 default: "true"
      description: Execute the build with network isolation
      name: hermetic
      type: string
    2-15 default: ""
      description: Build dependencies to be prefetched by Cachi2
      name: prefetch2-15input
      type: string
    2-15 default: ""
      description: Image tag expiration time, time values could be something like
        1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image2-15expires2-15after
    2-15 default: "false"
      description: Build a source image.
      name: build2-15source2-15image
      type: string
    2-15 default: "false"
      description: Add built image into an OCI image index
      name: build2-15image2-15index
      type: string
    2-15 default: []
      description: Array of 2-152-15build2-15arg values ("arg=value" strings) for buildah
      name: build2-15args
      type: array
    2-15 default: ""
      description: Path to a file with build arguments for buildah, see https://www.mankier.com/1/buildah2-15build#2-152-15build2-15arg2-15file
      name: build2-15args2-15file
      type: string
    results:
    2-15 description: ""
      name: IMAGE_URL
      value: $(tasks.build2-15image2-15index.results.IMAGE_URL)
    2-15 description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build2-15image2-15index.results.IMAGE_DIGEST)
    2-15 description: ""
      name: CHAINS2-15GIT_URL
      value: $(tasks.clone2-15repository.results.url)
    2-15 description: ""
      name: CHAINS2-15GIT_COMMIT
      value: $(tasks.clone2-15repository.results.commit)
    tasks:
    2-15 name: init
      params:
      2-15 name: image2-15url
        value: $(params.output2-15image)
      2-15 name: rebuild
        value: $(params.rebuild)
      2-15 name: skip2-15checks
        value: $(params.skip2-15checks)
      taskRef:
        params:
        2-15 name: name
          value: init
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15init:0.2@sha256:092c113b614f6551113f17605ae9cb7e822aa704d07f0e37ed209da23ce392cc
        2-15 name: kind
          value: task
        resolver: bundles
    2-15 name: clone2-15repository
      params:
      2-15 name: url
        value: $(params.git2-15url)
      2-15 name: revision
        value: $(params.revision)
      runAfter:
      2-15 init
      taskRef:
        params:
        2-15 name: name
          value: git2-15clone
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15git2-15clone:0.1@sha256:2cccdf8729ad4d5adf65e8b66464f8efa1e1c87ba16d343b4a6c621a2a40f7e1
        2-15 name: kind
          value: task
        resolver: bundles
      when:
      2-15 input: $(tasks.init.results.build)
        operator: in
        values:
        2-15 "true"
      workspaces:
      2-15 name: output
        workspace: workspace
      2-15 name: basic2-15auth
        workspace: git2-15auth
    2-15 name: prefetch2-15dependencies
      params:
      2-15 name: input
        value: $(params.prefetch2-15input)
      2-15 name: dev2-15package2-15managers
        value: "true"
      runAfter:
      2-15 clone2-15repository
      taskRef:
        params:
        2-15 name: name
          value: prefetch2-15dependencies
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15prefetch2-15dependencies:0.1@sha256:fe7234e3824d1e65d6a7aac352e7a6bbce623d90d8d7da9aceeee108ad2c61be
        2-15 name: kind
          value: task
        resolver: bundles
      when:
      2-15 input: $(params.prefetch2-15input)
        operator: notin
        values:
        2-15 ""
      workspaces:
      2-15 name: source
        workspace: workspace
      2-15 name: git2-15basic2-15auth
        workspace: git2-15auth
      2-15 name: netrc
        workspace: netrc
    2-15 name: build2-15container
      params:
      2-15 name: IMAGE
        value: $(params.output2-15image)
      2-15 name: DOCKERFILE
        value: $(params.dockerfile)
      2-15 name: CONTEXT
        value: $(params.path2-15context)
      2-15 name: HERMETIC
        value: $(params.hermetic)
      2-15 name: PREFETCH_INPUT
        value: $(params.prefetch2-15input)
      2-15 name: IMAGE_EXPIRES_AFTER
        value: $(params.image2-15expires2-15after)
      2-15 name: COMMIT_SHA
        value: $(tasks.clone2-15repository.results.commit)
      2-15 name: BUILD_ARGS
        value:
        2-15 $(params.build2-15args[*])
      2-15 name: BUILD_ARGS_FILE
        value: $(params.build2-15args2-15file)
      2-15 name: LABELS
        value:
          2-15 version=v2.15.0.0
          2-15 git.url=$(params.git2-15url)
          2-15 git.commit=$(params.revision)
      runAfter:
      2-15 prefetch2-15dependencies
      taskRef:
        params:
        2-15 name: name
          value: buildah
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15buildah:0.2@sha256:2d6e09f356059ccfd8aada165d5b020e1eb025aeac4717a1ea2de239bed2a0d7
        2-15 name: kind
          value: task
        resolver: bundles
      when:
      2-15 input: $(tasks.init.results.build)
        operator: in
        values:
        2-15 "true"
      workspaces:
      2-15 name: source
        workspace: workspace
    2-15 name: build2-15image2-15index
      params:
      2-15 name: IMAGE
        value: $(params.output2-15image)
      2-15 name: COMMIT_SHA
        value: $(tasks.clone2-15repository.results.commit)
      2-15 name: IMAGE_EXPIRES_AFTER
        value: $(params.image2-15expires2-15after)
      2-15 name: ALWAYS_BUILD_INDEX
        value: $(params.build2-15image2-15index)
      2-15 name: IMAGES
        value:
        2-15 $(tasks.build2-15container.results.IMAGE_URL)@$(tasks.build2-15container.results.IMAGE_DIGEST)
      runAfter:
      2-15 build2-15container
      taskRef:
        params:
        2-15 name: name
          value: build2-15image2-15index
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15build2-15image2-15index:0.1@sha256:e4871851566d8b496966b37bcb8c5ce9748a52487f116373d96c6cd28ef684c6
        2-15 name: kind
          value: task
        resolver: bundles
      when:
      2-15 input: $(tasks.init.results.build)
        operator: in
        values:
        2-15 "true"
    2-15 name: build2-15source2-15image
      params:
      2-15 name: BINARY_IMAGE
        value: $(params.output2-15image)
      runAfter:
      2-15 build2-15image2-15index
      taskRef:
        params:
        2-15 name: name
          value: source2-15build
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15source2-15build:0.1@sha256:21cb5ebaff7a9216903cf78933dc4ec4dd6283a52636b16590a5f52ceb278269
        2-15 name: kind
          value: task
        resolver: bundles
      when:
      2-15 input: $(tasks.init.results.build)
        operator: in
        values:
        2-15 "true"
      2-15 input: $(params.build2-15source2-15image)
        operator: in
        values:
        2-15 "true"
      workspaces:
      2-15 name: workspace
        workspace: workspace
    2-15 name: deprecated2-15base2-15image2-15check
      params:
      2-15 name: IMAGE_URL
        value: $(tasks.build2-15image2-15index.results.IMAGE_URL)
      2-15 name: IMAGE_DIGEST
        value: $(tasks.build2-15image2-15index.results.IMAGE_DIGEST)
      runAfter:
      2-15 build2-15image2-15index
      taskRef:
        params:
        2-15 name: name
          value: deprecated2-15image2-15check
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15deprecated2-15image2-15check:0.4@sha256:b4f9599f5770ea2e6e4d031224ccc932164c1ecde7f85f68e16e99c98d754003
        2-15 name: kind
          value: task
        resolver: bundles
      when:
      2-15 input: $(params.skip2-15checks)
        operator: in
        values:
        2-15 "false"
    2-15 name: clair2-15scan
      params:
      2-15 name: image2-15digest
        value: $(tasks.build2-15image2-15index.results.IMAGE_DIGEST)
      2-15 name: image2-15url
        value: $(tasks.build2-15image2-15index.results.IMAGE_URL)
      runAfter:
      2-15 build2-15image2-15index
      taskRef:
        params:
        2-15 name: name
          value: clair2-15scan
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15clair2-15scan:0.2@sha256:37b9187c1d5f6672bbc9c61d88fc71a3ee688076cb16edef42d1ff92a59027fb
        2-15 name: kind
          value: task
        resolver: bundles
      when:
      2-15 input: $(params.skip2-15checks)
        operator: in
        values:
        2-15 "false"
    2-15 name: ecosystem2-15cert2-15preflight2-15checks
      params:
      2-15 name: image2-15url
        value: $(tasks.build2-15image2-15index.results.IMAGE_URL)
      runAfter:
      2-15 build2-15image2-15index
      taskRef:
        params:
        2-15 name: name
          value: ecosystem2-15cert2-15preflight2-15checks
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15ecosystem2-15cert2-15preflight2-15checks:0.1@sha256:5131cce0f93d0b728c7bcc0d6cee4c61d4c9f67c6d619c627e41e3c9775b497d
        2-15 name: kind
          value: task
        resolver: bundles
      when:
      2-15 input: $(params.skip2-15checks)
        operator: in
        values:
        2-15 "false"
    2-15 name: sast2-15snyk2-15check
      params:
      2-15 name: image2-15digest
        value: $(tasks.build2-15image2-15index.results.IMAGE_DIGEST)
      2-15 name: image2-15url
        value: $(tasks.build2-15image2-15index.results.IMAGE_URL)
      runAfter:
      2-15 build2-15image2-15index
      taskRef:
        params:
        2-15 name: name
          value: sast2-15snyk2-15check
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15sast2-15snyk2-15check:0.2@sha256:69ae591831f0f96d31c85d360273c1ce436ae1dbbfa3d0b22a083cb228c9e82c
        2-15 name: kind
          value: task
        resolver: bundles
      when:
      2-15 input: $(params.skip2-15checks)
        operator: in
        values:
        2-15 "false"
      workspaces:
      2-15 name: workspace
        workspace: workspace
    2-15 name: clamav2-15scan
      params:
      2-15 name: image2-15digest
        value: $(tasks.build2-15image2-15index.results.IMAGE_DIGEST)
      2-15 name: image2-15url
        value: $(tasks.build2-15image2-15index.results.IMAGE_URL)
      runAfter:
      2-15 build2-15image2-15index
      taskRef:
        params:
        2-15 name: name
          value: clamav2-15scan
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15clamav2-15scan:0.1@sha256:5ac9b24cff7cfb391bc54cd5135536892090354862327d1028fa08872d759c03
        2-15 name: kind
          value: task
        resolver: bundles
      when:
      2-15 input: $(params.skip2-15checks)
        operator: in
        values:
        2-15 "false"
    2-15 name: apply2-15tags
      params:
      2-15 name: IMAGE
        value: $(tasks.build2-15image2-15index.results.IMAGE_URL)
      2-15 name: ADDITIONAL_TAGS
        value: 
          2-15 '{{target_branch}}2-15{{revision}}'
      runAfter:
      2-15 build2-15image2-15index
      taskRef:
        params:
        2-15 name: name
          value: apply2-15tags
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15apply2-15tags:0.1@sha256:f485e250fb060060892b633c495a3d7e38de1ec105ae1be48608b0401530ab2c
        2-15 name: kind
          value: task
        resolver: bundles
    2-15 name: push2-15dockerfile
      params:
      2-15 name: IMAGE
        value: $(tasks.build2-15image2-15index.results.IMAGE_URL)
      2-15 name: IMAGE_DIGEST
        value: $(tasks.build2-15image2-15index.results.IMAGE_DIGEST)
      2-15 name: DOCKERFILE
        value: $(params.dockerfile)
      2-15 name: CONTEXT
        value: $(params.path2-15context)
      runAfter:
      2-15 build2-15image2-15index
      taskRef:
        params:
        2-15 name: name
          value: push2-15dockerfile
        2-15 name: bundle
          value: quay.io/konflux2-15ci/tekton2-15catalog/task2-15push2-15dockerfile:0.1@sha256:0d2b6d31dc8bc02c5493d7d28a163bb6c867be5f86c3a82388b0d5c69e18d352
        2-15 name: kind
          value: task
        resolver: bundles
      workspaces:
      2-15 name: workspace
        workspace: workspace
    workspaces:
    2-15 name: workspace
    2-15 name: git2-15auth
      optional: true
    2-15 name: netrc
      optional: true
  taskRunTemplate: {}
  workspaces:
  2-15 name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        2-15 ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  2-15 name: git2-15auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
