name: PR Trigger

on:
  pull_request:
    types: [opened, reopened]

jobs:
  process_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v2

      - name: Download Python script, repos.json, and requirements.txt
        run: |
          curl -O https://raw.githubusercontent.com/MohammadiIram/test-automerger/main/pr.py
          curl -O https://raw.githubusercontent.com/MohammadiIram/test-automerger/main/repos.json
          curl -O https://raw.githubusercontent.com/MohammadiIram/test-automerger/main/requirements.txt
          curl -O https://raw.githubusercontent.com/rhoai-rhtap/RHOAI-Konflux-Automation/main/Konflux-auto-merger/pcam-release.yaml
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PR processing script
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GH }}
        run: |
          python pr.py
