name: PR Trigger

on:
  pull_request:
    types: [opened, reopened]

jobs:
  process_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v2

      - name: Download Python script and config file from test-automerger repository
        run: |
          curl -o pr.py https://raw.githubusercontent.com/MohammadiIram/test-automerger/main/pr.py
          curl -o repos.json https://raw.githubusercontent.com/MohammadiIram/test-automerger/main/repos.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Run PR processing script
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python pr.py
